window.EVRIS_PRODUCTS = [
  {
    id: "citrine-pearl-necklace",
    title: "Citrine Pearl Necklace",
    category: "necklace",
    meta: "Necklace / Silver",
    priceValue: 588,
    image: "assets/products/citrine-pearl-necklace.jpg",
    imageAlt: "Citrine pearl necklace",
    badge: "New",
    description:
      "A delicate silver necklace finished with soft pearl accents and a warm citrine tone for clean daily styling.",
    material: "Silver-tone chain, pearl accent, citrine-color crystal",
    style: "Layer with a white shirt or wear alone with a fine knit.",
  },
  {
    id: "citrine-pearl-bracelet",
    title: "Citrine Pearl Bracelet",
    category: "bracelet",
    meta: "Bracelet / Natural stone",
    priceValue: 358,
    image: "assets/products/citrine-pearl-bracelet.jpg",
    imageAlt: "Citrine pearl bracelet",
    badge: "Ranking 01",
    description:
      "A natural-stone bracelet with gentle yellow clarity and pearl shine, made for easy everyday layering.",
    material: "Natural stone beads, freshwater pearl accent, elastic cord",
    style: "Pairs well with denim, ivory cotton, and other slim bracelets.",
  },
  {
    id: "citrine-drop-earrings",
    title: "Citrine Drop Earrings",
    category: "earring",
    meta: "Earrings / Crystal",
    priceValue: 278,
    image: "assets/products/citrine-drop-earrings.jpg",
    imageAlt: "Citrine drop earrings",
    badge: "Light",
    description:
      "Light drop earrings with a warm crystal finish that adds brightness without feeling heavy.",
    material: "Crystal drop, silver-tone fitting",
    style: "Best with tucked hair, soft tailoring, or a simple camisole.",
  },
  {
    id: "baroque-arc-earrings",
    title: "Baroque Arc Earrings",
    category: "earring",
    meta: "Earrings / Freshwater pearl",
    priceValue: 198,
    image: "assets/products/baroque-arc-earrings.jpg",
    imageAlt: "Baroque arc pearl earrings",
    badge: "Gift",
    description:
      "Freshwater pearl earrings with a curved arc silhouette for a quiet statement near the face.",
    material: "Freshwater pearl, silver-tone arc fitting",
    style: "Wear with a clean neckline or a low bun for an elegant line.",
  },
  {
    id: "tiger-eye-bracelet",
    title: "Tiger Eye Bracelet",
    category: "bracelet",
    meta: "Bracelet / Stone mix",
    priceValue: 428,
    image: "assets/products/tiger-eye-bracelet.jpg",
    imageAlt: "Tiger eye natural stone bracelet",
    badge: "Stone",
    description:
      "A warm tiger-eye stone mix with subtle movement in the beads, balanced by a polished daily shape.",
    material: "Tiger eye stone, stone mix beads, elastic cord",
    style: "Adds depth to black, cream, gray, and brown outfits.",
  },
  {
    id: "clear-crystal-bracelet",
    title: "Clear Crystal Bracelet",
    category: "bracelet",
    meta: "Bracelet / White crystal",
    priceValue: 488,
    image: "assets/products/clear-crystal-bracelet.jpg",
    imageAlt: "Clear crystal bracelet with pearls",
    badge: "Clean",
    description:
      "A clear crystal bracelet with pearl details for a bright, minimal accent on the wrist.",
    material: "White crystal, pearl accent, elastic cord",
    style: "Layer with silver jewelry or keep solo for a clean finish.",
  },
  {
    id: "green-stone-bracelet",
    title: "Green Stone Bracelet",
    category: "bracelet",
    meta: "Bracelet / Daily color",
    priceValue: 308,
    image: "assets/products/green-stone-bracelet.jpg",
    imageAlt: "Green stone bracelet",
    badge: "Color",
    description: "A compact green stone bracelet designed to add calm color to everyday looks.",
    material: "Green stone beads, polished spacer details",
    style: "Works especially well with white, navy, soft gray, and linen.",
  },
  {
    id: "mix-stone-bracelet",
    title: "Mix Stone Bracelet",
    category: "bracelet",
    meta: "Bracelet / Color accent",
    priceValue: 388,
    image: "assets/products/mix-stone-bracelet.jpg",
    imageAlt: "Mixed color stone bracelet",
    badge: "Mix",
    description:
      "A playful color-accent bracelet with mixed stones while keeping the silhouette refined.",
    material: "Mixed natural stone beads, elastic cord",
    style: "Use as the color point with simple shirts or neutral dresses.",
  },
  {
    id: "moon-pearl-bracelet",
    title: "Moon Pearl Bracelet",
    category: "bracelet",
    meta: "Bracelet / Pearl",
    priceValue: 458,
    image: "assets/products/moon-pearl-bracelet.jpg",
    imageAlt: "Moon pearl bracelet",
    badge: "Pearl",
    description:
      "A pearl-forward bracelet with a moonlit sheen and a soft, rounded everyday presence.",
    material: "Pearl beads, silver-tone spacer details",
    style: "Beautiful with knitwear, satin, and relaxed evening styling.",
  },
  {
    id: "lapis-pearl-bracelet",
    title: "Lapis Pearl Bracelet",
    category: "bracelet",
    meta: "Bracelet / Blue stone",
    priceValue: 518,
    image: "assets/products/lapis-pearl-bracelet.jpg",
    imageAlt: "Lapis and pearl bracelet",
    badge: "Blue",
    description:
      "Deep blue lapis tones meet pearl softness for a bracelet with clean contrast and quiet color.",
    material: "Lapis-color stone beads, pearl accent, elastic cord",
    style: "Pairs neatly with denim, navy, white, and silver accessories.",
  },
  {
    id: "amber-pearl-bracelet",
    title: "Amber Pearl Bracelet",
    category: "bracelet",
    meta: "Bracelet / Warm stone",
    priceValue: 568,
    image: "assets/products/amber-pearl-bracelet.jpg",
    imageAlt: "Amber pearl bracelet",
    badge: "Warm",
    description:
      "A warm amber-tone bracelet softened by pearl accents for natural, feminine styling.",
    material: "Amber-color stone beads, pearl accent, elastic cord",
    style: "Adds warmth to ivory, charcoal, olive, and casual tailoring.",
  },
  {
    id: "minimal-pearl-chain",
    title: "Minimal Pearl Chain",
    category: "bracelet",
    meta: "Bracelet / Fine silver",
    priceValue: 298,
    image: "assets/products/minimal-pearl-chain.jpg",
    imageAlt: "Minimal pearl chain bracelet",
    badge: "Minimal",
    description:
      "A fine silver bracelet with a minimal pearl detail, made for subtle shine and easy stacking.",
    material: "Fine silver-tone chain, small pearl accent",
    style: "Wear alone for simplicity or stack with natural stone bracelets.",
  },
  {
    id: "aqua-pearl-bracelet",
    title: "Aqua Pearl Bracelet",
    category: "bracelet",
    meta: "Bracelet / Natural stone",
    priceValue: 538,
    image: "assets/products/aqua-pearl-bracelet.jpg",
    imageAlt: "Aqua stone and pearl bracelet",
    badge: "Editorial",
    description:
      "A soft blue stone bracelet made for ivory shirts, denim, and quiet summer styling.",
    material: "Aqua-tone natural stone beads, freshwater pearl accent",
    style: "Layer with fine silver or wear solo with airy cotton.",
  },
  {
    id: "smoky-quartz-bracelet",
    title: "Smoky Quartz Bracelet",
    category: "bracelet",
    meta: "Bracelet / Smoky stone",
    priceValue: 498,
    image: "assets/products/smoky-quartz-bracelet.jpg",
    imageAlt: "Smoky quartz bracelet",
    badge: "Limited",
    description: "A smoky quartz bracelet with quiet depth and a softened pearl finish.",
    material: "Smoky quartz-color stone, pearl accent, elastic cord",
    style: "Best with monochrome layers, soft knits, and silver rings.",
  },
  {
    id: "teal-pearl-bracelet",
    title: "Teal Pearl Bracelet",
    category: "bracelet",
    meta: "Bracelet / Teal stone",
    priceValue: 468,
    image: "assets/products/teal-pearl-bracelet.jpg",
    imageAlt: "Teal pearl bracelet",
    badge: "Online",
    description: "A teal-toned bracelet that brings a clean color accent to neutral styling.",
    material: "Teal-color stone beads, pearl accent, elastic cord",
    style: "Use with white denim, black tanks, and relaxed shirts.",
  },
  {
    id: "silver-lapis-bracelet",
    title: "Silver Lapis Bracelet",
    category: "bracelet",
    meta: "Bracelet / Lapis silver",
    priceValue: 548,
    image: "assets/products/silver-lapis-bracelet.jpg",
    imageAlt: "Silver lapis bracelet",
    badge: "Staff pick",
    description: "A lapis-color bracelet sharpened with silver-tone details for a cooler line.",
    material: "Lapis-color stone, silver-tone spacer details",
    style: "Clean with denim, navy, gray tailoring, and white shirts.",
  },
];
