const STONES = [
  {id:'001',slug:'amethyst',en:'AMETHYST',ja:'アメジスト',alias:'紫水晶',group:'QUARTZ',colors:['purple'],colorJa:'紫',mohs:'7',formula:'SiO₂',crystal:'三方晶系',origin:'ブラジル／ウルグアイ／ザンビア',birth:'2月',pos:'0% 0%',desc:'アメジストは紫色を特徴とする水晶の一種です。微量の鉄と自然放射線の影響によって、淡い紫から深い紫までさまざまな色合いを示します。'},
  {id:'002',slug:'rose-quartz',en:'ROSE QUARTZ',ja:'ローズクォーツ',alias:'紅水晶',group:'QUARTZ',colors:['pink'],colorJa:'ピンク',mohs:'7',formula:'SiO₂',crystal:'三方晶系',origin:'ブラジル／マダガスカル／インド',birth:'—',pos:'33.333% 0%',desc:'繊細な桃色を帯びる石英。微細な鉱物の包有物が光をやわらかく散乱させ、半透明の穏やかな表情をつくります。'},
  {id:'003',slug:'aquamarine',en:'AQUAMARINE',ja:'アクアマリン',alias:'藍玉',group:'BERYL',colors:['blue'],colorJa:'青',mohs:'7.5–8',formula:'Be₃Al₂Si₆O₁₈',crystal:'六方晶系',origin:'ブラジル／パキスタン／ナミビア',birth:'3月',pos:'66.666% 0%',desc:'海水を思わせる淡青色の緑柱石。結晶に含まれる鉄が、透明感のある青から青緑の色彩を生み出します。'},
  {id:'004',slug:'malachite',en:'MALACHITE',ja:'マラカイト',alias:'孔雀石',group:'CARBONATE',colors:['green'],colorJa:'緑',mohs:'3.5–4',formula:'Cu₂CO₃(OH)₂',crystal:'単斜晶系',origin:'コンゴ民主共和国／ザンビア／ロシア',birth:'—',pos:'100% 0%',desc:'濃淡のある緑の縞模様が特徴の銅鉱物。断面には同心円状の層が現れ、成長の時間を視覚的に残します。'},
  {id:'005',slug:'citrine',en:'CITRINE',ja:'シトリン',alias:'黄水晶',group:'QUARTZ',colors:['yellow'],colorJa:'黄',mohs:'7',formula:'SiO₂',crystal:'三方晶系',origin:'ブラジル／マダガスカル／ボリビア',birth:'11月',pos:'0% 33.333%',desc:'黄色から蜂蜜色を示す水晶。微量の鉄が色の源となり、天然の結晶は比較的希少です。'},
  {id:'006',slug:'garnet',en:'GARNET',ja:'ガーネット',alias:'柘榴石',group:'SILICATE',colors:['red'],colorJa:'赤',mohs:'6.5–7.5',formula:'X₃Y₂(SiO₄)₃',crystal:'等軸晶系',origin:'インド／スリランカ／タンザニア',birth:'1月',pos:'33.333% 33.333%',desc:'柘榴の実に似た深い赤で知られる鉱物グループ。成分の違いにより、緑や橙など幅広い色が存在します。'},
  {id:'007',slug:'labradorite',en:'LABRADORITE',ja:'ラブラドライト',alias:'曹灰長石',group:'FELDSPAR',colors:['blue','black'],colorJa:'青・灰',mohs:'6–6.5',formula:'(Ca,Na)(Al,Si)₄O₈',crystal:'三斜晶系',origin:'カナダ／マダガスカル／フィンランド',birth:'—',pos:'66.666% 33.333%',desc:'角度によって青や緑の光が浮かぶ長石。薄い層状構造で光が干渉し、ラブラドレッセンスが現れます。'},
  {id:'008',slug:'lapis-lazuli',en:'LAPIS LAZULI',ja:'ラピスラズリ',alias:'瑠璃',group:'ROCK',colors:['blue'],colorJa:'青',mohs:'5–5.5',formula:'複合鉱物',crystal:'等軸晶系（主成分）',origin:'アフガニスタン／チリ／ロシア',birth:'12月',pos:'100% 33.333%',desc:'ラズライトを主成分とする深い群青の岩石。白い方解石や金色の黄鉄鉱を含み、夜空のような模様を見せます。'},
  {id:'009',slug:'fluorite',en:'FLUORITE',ja:'フローライト',alias:'蛍石',group:'HALIDE',colors:['green','purple'],colorJa:'緑・紫',mohs:'4',formula:'CaF₂',crystal:'等軸晶系',origin:'中国／メキシコ／イギリス',birth:'—',pos:'0% 66.666%',desc:'立方体や八面体の結晶をつくる蛍石。緑、紫、青など色彩が豊かで、紫外線下で蛍光を示す標本もあります。'},
  {id:'010',slug:'obsidian',en:'OBSIDIAN',ja:'オブシディアン',alias:'黒曜石',group:'VOLCANIC GLASS',colors:['black'],colorJa:'黒',mohs:'5–5.5',formula:'SiO₂ 主体',crystal:'非晶質',origin:'メキシコ／アメリカ／日本',birth:'—',pos:'33.333% 66.666%',desc:'溶岩が急速に冷えて生まれた天然ガラス。結晶をほとんど持たず、割れ口は貝殻状の鋭い曲面になります。'},
  {id:'011',slug:'moonstone',en:'MOONSTONE',ja:'ムーンストーン',alias:'月長石',group:'FELDSPAR',colors:['white'],colorJa:'白',mohs:'6–6.5',formula:'KAlSi₃O₈',crystal:'単斜晶系',origin:'スリランカ／インド／タンザニア',birth:'6月',pos:'66.666% 66.666%',desc:'内部に月光のような青白い光が漂う長石。薄い層の境界で起こる光の散乱が、独特のシラーを生みます。'},
  {id:'012',slug:'clear-quartz',en:'CLEAR QUARTZ',ja:'水晶',alias:'石英',group:'QUARTZ',colors:['white'],colorJa:'透明',mohs:'7',formula:'SiO₂',crystal:'三方晶系',origin:'ブラジル／アメリカ／日本',birth:'4月',pos:'100% 66.666%',desc:'無色透明の石英。六角柱状の結晶と先端の錐面をもち、地殻を構成する代表的な鉱物のひとつです。'},
  {id:'013',slug:'tigers-eye',en:"TIGER'S EYE",ja:'タイガーアイ',alias:'虎目石',group:'QUARTZ',colors:['yellow'],colorJa:'茶・黄',mohs:'6.5–7',formula:'SiO₂',crystal:'三方晶系',origin:'南アフリカ／オーストラリア／ナミビア',birth:'—',pos:'0% 100%',desc:'繊維状構造を石英が置換してできた鉱物。光の帯が表面を横切るシャトヤンシーが虎の眼を思わせます。'},
  {id:'014',slug:'turquoise',en:'TURQUOISE',ja:'ターコイズ',alias:'トルコ石',group:'PHOSPHATE',colors:['blue','green'],colorJa:'青緑',mohs:'5–6',formula:'CuAl₆(PO₄)₄(OH)₈·4H₂O',crystal:'三斜晶系',origin:'イラン／アメリカ／中国',birth:'12月',pos:'33.333% 100%',desc:'乾燥地帯の銅鉱床で生まれる青緑色の鉱物。母岩が網目状に残るマトリックスも標本の個性です。'},
  {id:'015',slug:'carnelian',en:'CARNELIAN',ja:'カーネリアン',alias:'紅玉髄',group:'CHALCEDONY',colors:['orange','red'],colorJa:'橙',mohs:'6.5–7',formula:'SiO₂',crystal:'三方晶系',origin:'インド／ブラジル／ウルグアイ',birth:'7月',pos:'66.666% 100%',desc:'橙から赤褐色の半透明な玉髄。微細な石英結晶の集合体で、鉄酸化物が温かな色を与えます。'},
  {id:'016',slug:'rhodochrosite',en:'RHODOCHROSITE',ja:'ロードクロサイト',alias:'菱マンガン鉱',group:'CARBONATE',colors:['pink'],colorJa:'ピンク',mohs:'3.5–4',formula:'MnCO₃',crystal:'三方晶系',origin:'アルゼンチン／南アフリカ／アメリカ',birth:'—',pos:'100% 100%',desc:'マンガンを主成分とする桃色の炭酸塩鉱物。白とピンクの縞が重なる標本は、鍾乳状に成長した断面です。'}
];
